- name: deploy Airflow containers locally
  hosts: localhost
  vars:
    command: scheduler -n 5 # See bug 1286825
    compose_conf:
      - "{{ playbook_dir }}/files/docker-compose.yml"
      - "{{ playbook_dir }}/files/docker-compose-local.yml"

  tasks:
    - name: launch Airflow containers
      shell: "{{ item }}"
      with_items:
        - docker-compose -f {{ compose_conf[0] }} -f {{ compose_conf[1] }} down -v --remove-orphans
        - docker-compose -f {{ compose_conf[0] }} -f {{ compose_conf[1] }} up -d
      environment:
        AIRFLOW_ENABLE_AUTH: False
        FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        DB_URI: "{{ db_uri }}"
        DB_USER: "{{ db_user }}"
        DB_PASSWORD: "{{ db_password }}"
        DB_TABLE: "{{ db_table }}"
        SMTP_HOST: "localhost"
        SMTP_USER: "dummy"
        SMTP_PASSWORD: "dummy_pass"
        COMMAND: "{{ command }}"
